# Generated by Django 4.2.13 on 2024-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_address_1_profile_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
