# Generated by Django 5.0.7 on 2024-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile_cart_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
    ]
