# Generated by Django 5.0.7 on 2024-07-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='background',
        ),
    ]
